### ISSUE TITLE
lets: config error: file does not exist: lets.yaml

### ISSUE THREAD

**Issue by IcedQuinn** [lets-cli/lets#263]
- lets version 0.0.53

```
$ lets --init
lets: config error: file does not exist: lets.yaml
```

It seems Lets is checking for a config file prior to realizing it is being asked to create it.

**Comment by kindermax** [comment]
Yes, that is a silly bug 🥲 . Thank you for reporting it, will fix it in a while.

**Comment by kindermax** [comment]
Fix must be in https://github.com/lets-cli/lets/releases/tag/v0.0.54
