### ISSUE TITLE
Implement persistant storing of checksums

### ISSUE THREAD

**Issue by danylkaaa** [lets-cli/lets#33]
We need to store checksum persistent, if we want to be able to start working on #32

**Comment by kindritskyiMax** [comment]
My view of functionality:

0. add new option to command in yaml called `persist_checksum` - it is a boolean
1. create a folder called `.lets`  in the project directory (where `lets.yaml` exists)
2. in `.lets` folder there will be  a `checksum` folder
3. each checksum will be stored into a separate file called `{command}_{checksum_name_if_exists}`
4. when a command runs for the first time we write down new checksum into a file
5. when a command runs the second time we reading an old checksum from a file, calculating the new checksum, compare them and expose new environ variable `LETS_CHECKSUM_{NAME_OF_CHEKSUM_IF_EXISTS}_CHANGED` - a boolean
6. the most important thing - we replacing old checksum with a new checksum only if a command exits with status `0`. That is a command using a checksum persist must be as deterministic as possible - for example, `docker build` or `npm install`. That gives a guarantee that we replacing a checksum only if we make sure our command is completed successfully.

**Comment by danylkaaa** [comment]
Maybe we should creeate GitHub project board? And use it for releases?

**Comment by kindermax** [comment]
https://github.com/lets-cli/lets#persist_checksum \
https://github.com/lets-cli/lets/releases/tag/v0.0.20
