### ISSUE TITLE
go command

### ISSUE THREAD

**Issue by vharitonsky** [lets-cli/lets#78]
Basic built-in command which will generate default lets.yaml with hello world command inside, so it is very easy to introduce lets into a project. We can imagine a wizard asking basic defaults like shell type before generating the file.

**Comment by kindermax** [comment]
Great idea. We can start with a simple `--init` flag which generates hello world `lets.yaml` and then in separate PR we can implement some kind of wizard (although it seems like a place to sit and think about what we actually expect from this functionality)

**Comment by vharitonsky** [comment]
Shell choice seems to be obvious, also there can be a selection of example scripts to choose: helloworld/complex example(with depends, letsopt, checksum, etc.)
